### ISSUE TITLE
UniversalAccessFromFileUrlsAllowed and FileAccessFromFileUrlsAllowed doesn't work.

### ISSUE THREAD

**Issue by vasilm** [ataranto/CefSharp#25]
Hi,
I have an issue showing my local images in the browser. I set UniversalAccessFromFileUrlsAllowed  and FileAccessFromFileUrlsAllowed  true but no result.

do you have any suggestion on this? I am using version 0.10 

vas

**Comment by ataranto** [comment]
I haven't used this myself. What happens when you try to open an image?

Try one of the following:
- Try the 0.11 release
- Try buliding from git (master branch or cef_update branch)
- Use [IBeforeResourceLoad](https://github.com/chillitom/CefSharp/blob/master/CefSharp/IBeforeResourceLoad.h) to load the image data.

**Comment by vasilm** [comment]
FileAccessFromFileUrlsAllowed doesn't work. (#25)
MIME-Version: 1.0
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: 7bit

Tried with 0.11 as well same behavior. Seems not implemented.
